theme: jekyll-theme-minimal
title: Devin Ho's Website
logo: https://media-exp1.licdn.com/dms/image/C5603AQFGp4PMyv-MJg/profile-displayphoto-shrink_800_800/0/1630523181276?e=1639008000&v=beta&t=GLoOlwB_ePVV0M5hSPSU3OjPbIlV_q9k4409wZoKWGA
description: A website about Devin Ho.
